# Generated by Django 2.2.1 on 2019-05-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredientName',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipeName',
        ),
    ]
