# Generated by Django 2.2.1 on 2019-05-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190525_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredientName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeName',
            new_name='name',
        ),
    ]
